### ISSUE TITLE
Issues with FIRST in IDA 7.2

### ISSUE THREAD

**Issue by recvfrom** [vrtadmin/FIRST-plugin-ida#20]
When a program is being analyzed, the following error messages get displayed a lot in IDA 7.2:
```
Exception in IDP Hook function: SWIG director method error. Error detected when calling 'IDP_Hooks.ev_auto_queue_empty'
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.2/plugins/first.py", line 3376, in ev_auto_queue_empty
    return self.auto_queue_empty(arg, before7=False)
  File "C:/Program Files/IDA 7.2/plugins/first.py", line 3419, in auto_queue_empty
    return super(self.__class__, self).ev_auto_queue_empty(arg)
  File "C:\Program Files\IDA 7.2\python\ida_ida.py", line 1108, in __wrapper
    rc = do_call(cb, *args)
  File "C:\Program Files\IDA 7.2\python\ida_idp.py", line 3174, in __call_IDP_Hooks_auto_queue_empty
    old_rc = cb(qtype)
  File "C:/Program Files/IDA 7.2/plugins/first.py", line 3418, in auto_queue_empty
    return super(self.__class__, self).auto_queue_empty(arg)
AttributeError: 'super' object has no attribute 'auto_queue_empty'
```

Also, when querying a function for metadata:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\Lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\Lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:/Program Files/IDA 7.2/plugins/first.py", line 2525, in __thread_scan
    'apis' : m.apis,
  File "C:/Program Files/IDA 7.2/plugins/first.py", line 1512, in apis
    self.__apis = FIRST.Info.get_apis(self.address)
  File "C:/Program Files/IDA 7.2/plugins/first.py", line 1014, in get_apis
    for instr in IDAW.FuncItems(address):
  File "C:\Program Files\IDA 7.2\python\idautils.py", line 326, in FuncItems
    func = ida_funcs.get_func(start)
  File "C:\Program Files\IDA 7.2\python\ida_funcs.py", line 492, in get_func
    return _ida_funcs.get_func(*args)
RuntimeError: Function can be called from the main thread only
```

**Comment by jellever** [comment]
+1 Support for 7.2 is broken

**Comment by recvfrom** [comment]
The first exception above was fixed via https://github.com/vrtadmin/FIRST-plugin-ida/commit/5c20ff836fa440a7cf12bc680cb60db7072c5cf6 in the dev branch.  The second exception above is fixed via https://github.com/vrtadmin/FIRST-plugin-ida/pull/21 (also in the dev branch).  The dev branch should be merged to master soon

**Comment by jellever** [comment]
I run IDA 7.2 with FIRST (latest Dev branch) and still have issues:

`Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)] 
IDAPython v1.7.0 final (serial 0) (c) The IDAPython Team <idapython@googlegroups.com>
--------------------------------------------------------------------------------------
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27_64\Lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Python27_64\Lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:/Program Files/IDA 7.2/plugins/first.py", line 2555, in __thread_scan
    'apis' : m.apis,
  File "C:/Program Files/IDA 7.2/plugins/first.py", line 1542, in apis
    self.__apis = FIRST.Info.get_apis(self.address)
  File "C:/Program Files/IDA 7.2/plugins/first.py", line 1044, in get_apis
    for instr in IDAW.FuncItems(address):
  File "C:\Program Files\IDA 7.2\python\idautils.py", line 326, in FuncItems
    func = ida_funcs.get_func(start)
  File "C:\Program Files\IDA 7.2\python\ida_funcs.py", line 492, in get_func
    return _ida_funcs.get_func(*args)
RuntimeError: Function can be called from the main thread only`

**Comment by recvfrom** [comment]
@jellever it looks like that stack trace is from before the changes introduced via #21.  Specifically,
```
  File "C:/Program Files/IDA 7.2/plugins/first.py", line 1044, in get_apis
    for instr in IDAW.FuncItems(address):
```
has been replaced with:
```
  File "C:/Program Files/IDA 7.2/plugins/first.py", line 1080, in get_apis
    for instr in safe_generator(IDAW.FuncItems(address)):
```
https://github.com/vrtadmin/FIRST-plugin-ida/blob/dev/first_plugin_ida/first.py#L1080

**Comment by jellever** [comment]
Hmmm might have made a mistake installing the latest version. I'll reinstall the latest version and come back to you :)

**Comment by recvfrom** [comment]
Now the dev has been merged into master, this ticket can be closed
